POST https://nodedozero-d4xz.onrender.com/videos
Content-type: application/json
Accept-Language: pt-Br

{
    "title": "Video de node1",
    "description": "Descrição do video de teste",
    "duration": 180
}

###

GET https://nodedozero-d4xz.onrender.com/videos

###

PUT https://nodedozero-d4xz.onrender.com/videos/
Content-type: application/json

{
    "title": "Video de Teste1",
    "description": "Descrição do video de teste",
    "duration": 180
}

###

DELETE https://nodedozero-d4xz.onrender.com/videos/